<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1.5 Hypothesis Testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="1.5 Hypothesis Testing_files/libs/clipboard/clipboard.min.js"></script>
<script src="1.5 Hypothesis Testing_files/libs/quarto-html/quarto.js"></script>
<script src="1.5 Hypothesis Testing_files/libs/quarto-html/popper.min.js"></script>
<script src="1.5 Hypothesis Testing_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="1.5 Hypothesis Testing_files/libs/quarto-html/anchor.min.js"></script>
<link href="1.5 Hypothesis Testing_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="1.5 Hypothesis Testing_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="1.5 Hypothesis Testing_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="1.5 Hypothesis Testing_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="1.5 Hypothesis Testing_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">
<div style="text-align: center;">
  <img src="images/department_logo.png" width="169">
  <img src="images/ioa_logo.png" width="122">
  <img src="images/petra_logo.png" width="52">
</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">1.5 Hypothesis Testing</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="inferential-statistics---hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="inferential-statistics---hypothesis-testing">Inferential Statistics - Hypothesis Testing</h2>
<section id="introduction-to-hypothesis-testing" class="level4">
<h4 class="anchored" data-anchor-id="introduction-to-hypothesis-testing">1. Introduction to Hypothesis Testing</h4>
<ul>
<li>Definition and Importance</li>
<li>Null Hypothesis (H0) and Alternative Hypothesis (H1)</li>
<li>Types of Errors
<ul>
<li>Type I Error (False Positive)</li>
<li>Type II Error (False Negative)</li>
</ul></li>
<li>Significance Level (α)</li>
</ul>
</section>
<section id="steps-in-hypothesis-testing" class="level4">
<h4 class="anchored" data-anchor-id="steps-in-hypothesis-testing">2. Steps in Hypothesis Testing</h4>
<ul>
<li>Formulating Hypotheses</li>
<li>Choosing the Appropriate Test</li>
<li>Determining the Significance Level</li>
<li>Calculating the Test Statistic</li>
<li>Making a Decision</li>
<li>Interpreting Results</li>
</ul>
</section>
<section id="types-of-hypothesis-tests" class="level4">
<h4 class="anchored" data-anchor-id="types-of-hypothesis-tests">3. Types of Hypothesis Tests</h4>
<ul>
<li>One-tailed vs.&nbsp;Two-tailed Tests
<ul>
<li>Definition and Differences</li>
<li>When to Use Each Type</li>
</ul></li>
</ul>
</section>
<section id="parametric-tests" class="level4">
<h4 class="anchored" data-anchor-id="parametric-tests">4. Parametric Tests</h4>
<ul>
<li>Z-test
<ul>
<li>One-sample Z-test</li>
<li>Two-sample Z-test</li>
<li>Assumptions and Applications</li>
</ul></li>
<li>T-test
<ul>
<li>One-sample T-test</li>
<li>Independent Two-sample T-test</li>
<li>Paired Sample T-test</li>
<li>Assumptions and Applications</li>
</ul></li>
<li>ANOVA (Analysis of Variance)
<ul>
<li>One-way ANOVA</li>
<li>Two-way ANOVA</li>
<li>Assumptions and Applications</li>
</ul></li>
</ul>
</section>
<section id="non-parametric-tests" class="level4">
<h4 class="anchored" data-anchor-id="non-parametric-tests">5. Non-parametric Tests</h4>
<ul>
<li>Chi-square Test
<ul>
<li>Chi-square Test for Independence</li>
<li>Chi-square Goodness of Fit Test</li>
<li>Assumptions and Applications</li>
</ul></li>
<li>Mann-Whitney U Test
<ul>
<li>Definition and Application</li>
</ul></li>
<li>Wilcoxon Signed-Rank Test
<ul>
<li>Definition and Application</li>
</ul></li>
<li>Kruskal-Wallis Test
<ul>
<li>Definition and Application</li>
</ul></li>
</ul>
</section>
<section id="test-assumptions-and-conditions" class="level4">
<h4 class="anchored" data-anchor-id="test-assumptions-and-conditions">6. Test Assumptions and Conditions</h4>
<ul>
<li>Normality</li>
<li>Homogeneity of Variances</li>
<li>Independence</li>
<li>Handling Violations of Assumptions</li>
</ul>
</section>
<section id="power-of-a-test" class="level4">
<h4 class="anchored" data-anchor-id="power-of-a-test">7. Power of a Test</h4>
<ul>
<li>Definition and Importance</li>
<li>Factors Affecting Power</li>
<li>Calculating and Interpreting Power</li>
</ul>
</section>
<section id="p-value-and-statistical-significance" class="level4">
<h4 class="anchored" data-anchor-id="p-value-and-statistical-significance">8. P-value and Statistical Significance</h4>
<ul>
<li>Definition and Interpretation</li>
<li>Misconceptions and Common Pitfalls</li>
</ul>
</section>
<section id="effect-size" class="level4">
<h4 class="anchored" data-anchor-id="effect-size">9. Effect Size</h4>
<ul>
<li>Definition and Importance</li>
<li>Common Measures of Effect Size (Cohen’s d, Pearson’s r, etc.)</li>
</ul>
</section>
<section id="hypothesis-testing-in-r" class="level4">
<h4 class="anchored" data-anchor-id="hypothesis-testing-in-r">10. Hypothesis Testing in R</h4>
<ul>
<li>Conducting Z-tests and T-tests</li>
<li>Performing ANOVA</li>
<li>Running Chi-square Tests</li>
<li>Implementing Non-parametric Tests</li>
<li>Visualizing Test Results</li>
</ul>
</section>
<section id="summary-of-tests" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-tests">Summary of Tests</h3>
<p>Here’s a table summarizing the parametric tests and their non-parametric counterparts, including any missing important tests:</p>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Parametric Test</th>
<th>Use</th>
<th>Assumptions</th>
<th>Interpretation</th>
<th>Non-Parametric Counterpart</th>
<th>Use</th>
<th>Assumptions</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-sample T-test</td>
<td>Test if the mean of a single sample differs from a known mean.</td>
<td>Normality, independence</td>
<td>p-value &lt; 0.05 indicates significant difference from the known mean.</td>
<td>One-sample Wilcoxon Signed-Rank Test</td>
<td>Test if the median of a single sample differs from a known median.</td>
<td>Symmetric distribution, independence</td>
<td>p-value &lt; 0.05 indicates significant difference from the known median.</td>
</tr>
<tr class="even">
<td>Two-sample T-test (Independent)</td>
<td>Compare the means of two independent samples.</td>
<td>Independence, normality, equal variances</td>
<td>p-value &lt; 0.05 indicates significant difference between means.</td>
<td>Mann-Whitney U Test (Wilcoxon Rank-Sum Test)</td>
<td>Compare distributions of two independent samples.</td>
<td>Independence, ordinal/continuous data, similar shapes</td>
<td>p-value &lt; 0.05 indicates significant difference in distributions.</td>
</tr>
<tr class="odd">
<td>Paired Sample T-test</td>
<td>Compare means of two related samples.</td>
<td>Normality of differences, independence of pairs</td>
<td>p-value &lt; 0.05 indicates significant difference between paired samples.</td>
<td>Wilcoxon Signed-Rank Test</td>
<td>Compare distributions of two related samples.</td>
<td>Symmetric differences, independence of pairs</td>
<td>p-value &lt; 0.05 indicates significant difference in distributions.</td>
</tr>
<tr class="even">
<td>One-way ANOVA</td>
<td>Compare means of three or more groups.</td>
<td>Normality, homogeneity of variances, independence</td>
<td>p-value &lt; 0.05 indicates significant difference among group means.</td>
<td>Kruskal-Wallis Test</td>
<td>Compare distributions of three or more independent groups.</td>
<td>Independence, ordinal/continuous data, similar shapes</td>
<td>p-value &lt; 0.05 indicates significant difference among group distributions.</td>
</tr>
<tr class="odd">
<td>Chi-square Test for Independence</td>
<td>Test for association between two categorical variables.</td>
<td>Count data, independence, expected frequencies ≥ 5</td>
<td>p-value &lt; 0.05 indicates significant association.</td>
<td>Fisher’s Exact Test</td>
<td>Test for association between two categorical variables (small sample sizes).</td>
<td>Count data, independence, small sample sizes</td>
<td>p-value &lt; 0.05 indicates significant association.</td>
</tr>
<tr class="even">
<td>Pearson Correlation</td>
<td>Measure linear relationship between two continuous variables.</td>
<td>Normality, linearity, homoscedasticity</td>
<td>p-value &lt; 0.05 indicates significant correlation.</td>
<td>Spearman’s Rank Correlation</td>
<td>Measure monotonic relationship between two continuous/ordinal variables.</td>
<td>Ordinal/continuous data, monotonic relationship</td>
<td>p-value &lt; 0.05 indicates significant correlation.</td>
</tr>
<tr class="odd">
<td>Two-way ANOVA</td>
<td>Compare means of groups split on two factors.</td>
<td>Normality, homogeneity of variances, independence</td>
<td>p-value &lt; 0.05 indicates significant interaction or main effects.</td>
<td>Friedman Test</td>
<td>Compare distributions of groups split on two factors.</td>
<td>Ordinal data, independence, blocks</td>
<td>p-value &lt; 0.05 indicates significant interaction or main effects.</td>
</tr>
<tr class="even">
<td>Linear Regression</td>
<td>Predict a continuous outcome based on one or more predictors.</td>
<td>Linearity, independence, homoscedasticity, normality of residuals</td>
<td>p-value &lt; 0.05 indicates significant predictors.</td>
<td>Non-parametric Regression (e.g., LOESS)</td>
<td>Predict a continuous outcome without assuming a specific form of relationship.</td>
<td>Assumptions vary based on method used</td>
<td>p-value &lt; 0.05 indicates significant predictors or relationships.</td>
</tr>
</tbody>
</table>
<section id="practical-examples-and-exercises" class="level4">
<h4 class="anchored" data-anchor-id="practical-examples-and-exercises">Practical Examples and Exercises</h4>
<p>Certainly! Here is the documentation with the assumptions for each test included:</p>
</section>
</section>
<section id="one-sample-t-test" class="level3">
<h3 class="anchored" data-anchor-id="one-sample-t-test">1. One-sample T-test</h3>
<p><strong>Use:</strong> To test if the mean of a single sample is significantly different from a known or hypothesized population mean.</p>
<p><strong>Assumptions:</strong> - The sample data is normally distributed. - The sample observations are independent.</p>
<p><strong>Example:</strong>- Suppose we want to test if the average satisfaction score of customers for a new product is significantly different from the target satisfaction score of 5.</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate customer satisfaction scores</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>satisfaction_scores <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-sample t-test to test if the mean satisfaction score is significantly different from 5</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(satisfaction_scores, <span class="at">mu =</span> <span class="dv">5</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the satisfaction scores</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(satisfaction_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.879049 4.539645 8.117417 5.141017 5.258575 8.430130 5.921832 2.469878
 [9] 3.626294 4.108676 7.448164 5.719628 5.801543 5.221365 3.888318 8.573826
[17] 5.995701 1.066766 6.402712 4.054417 2.864353 4.564050 2.947991 3.542218
[25] 3.749921 1.626613 6.675574 5.306746 2.723726 7.507630</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test result</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  satisfaction_scores
t = -0.26299, df = 29, p-value = 0.7944
alternative hypothesis: true mean is not equal to 5
95 percent confidence interval:
 4.173147 5.638438
sample estimates:
mean of x 
 4.905792 </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p><strong>Satisfaction Scores:</strong> Generated customer satisfaction scores with a mean of approximately 5.</p>
<ul>
<li><p><strong>T-test Result:</strong></p>
<ul>
<li><p><strong>t:</strong> Test statistic (-0.26299)</p></li>
<li><p><strong>df:</strong> Degrees of freedom (29)</p></li>
<li><p><strong>p-value:</strong> Probability of observing the data if the null hypothesis is true (0.7944)</p></li>
<li><p><strong>95% Confidence Interval:</strong> Range within which the true mean lies with 95% confidence (4.173147 to 5.638438)</p></li>
<li><p><strong>Sample Mean (mean of x):</strong> Average satisfaction score (4.905792)</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.7944) is greater than the common significance level (0.05), we fail to reject the null hypothesis.</p>
<p>This indicates that the average satisfaction score is not significantly different from the target score of 5.</p>
</section>
<section id="two-sample-t-test-independent" class="level3">
<h3 class="anchored" data-anchor-id="two-sample-t-test-independent">2. Two-sample T-test (Independent)</h3>
<p><strong>Use:</strong> To compare the means of two independent samples to see if they are significantly different.</p>
<p><strong>Assumptions:</strong> - The samples are independent of each other. - The data in each sample is normally distributed. - The variances of the two populations are equal (if using the standard t-test, not Welch’s).</p>
<p>Example:- Suppose we want to test if there is a significant difference in average performance scores between employees who received training and those who did not.</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate performance scores for two groups</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>trained_employees <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">75</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Employees who received training</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>untrained_employees <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">70</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Employees who did not receive training</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform two-sample t-test to compare the mean performance scores between trained and untrained employees</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(trained_employees, untrained_employees)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the performance scores</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(trained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 69.39524 72.69823 90.58708 75.70508 76.29288 92.15065 79.60916 62.34939
 [9] 68.13147 70.54338 87.24082 78.59814 79.00771 76.10683 69.44159 92.86913
[17] 79.97850 55.33383 82.01356 70.27209 64.32176 72.82025 64.73996 67.71109
[25] 68.74961 58.13307 83.37787 76.53373 63.61863 87.53815</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(untrained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 74.26464 67.04929 78.95126 78.78133 78.21581 76.88640 75.53918 69.38088
 [9] 66.94037 66.19529 63.05293 67.92083 57.34604 91.68956 82.07962 58.76891
[17] 65.97115 65.33345 77.79965 69.16631 72.53319 69.71453 69.57130 83.68602
[25] 67.74229 85.16471 54.51247 75.84614 71.23854 72.15942</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test result</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  trained_employees and untrained_employees
t = 1.1672, df = 56.559, p-value = 0.248
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.965426  7.456584
sample estimates:
mean of x mean of y 
 74.52896  71.78338 </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Performance Scores:</strong></p>
<ul>
<li><p><strong>Trained Employees:</strong> Generated performance scores with a mean of approximately 75.</p></li>
<li><p><strong>Untrained Employees:</strong> Generated performance scores with a mean of approximately 70.</p></li>
</ul></li>
<li><p><strong>T-test Result:</strong></p>
<ul>
<li><p><strong>t:</strong> Test statistic (1.672)</p></li>
<li><p><strong>df:</strong> Degrees of freedom (56.559)</p></li>
<li><p><strong>p-value:</strong> Probability of observing the data if the null hypothesis is true (0.248)</p></li>
<li><p><strong>95% Confidence Interval:</strong> Range within which the true mean difference lies with 95% confidence (-1.965426 to 7.456584)</p></li>
<li><p><strong>Sample Means (mean of x, mean of y):</strong> Average performance scores for trained employees (74.52896) and untrained employees (71.78338)</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.1104) is greater than the common significance level (0.05), we fail to reject the null hypothesis.</p>
<p>This indicates that there is no significant difference in average performance scores between trained and untrained employees</p>
<p>Note: althought the averages are quite difference, yet, the t-test showed that there is not significant difference. Here is the interpretation for that:</p>
<p>The two-sample t-test takes into account not only the difference in means but also the variability within each group and the sample size. Here are some possible reasons why the t-test might not find a significant difference even if the means appear different:</p>
<ol type="1">
<li><strong>Variability within Groups:</strong> If the variability (standard deviation) within each group is high, it can obscure the difference between the group means.</li>
<li><strong>Sample Size:</strong> Smaller sample sizes result in less precise estimates of the mean, making it harder to detect a significant difference.</li>
<li><strong>p-value and Significance Level:</strong> The p-value might not be less than the significance level (usually 0.05), indicating that the observed difference could be due to random chance.</li>
</ol>
<p>Let’s take a closer look at the standard deviations and sample sizes in your example. We will also plot the data to visualize the distributions.</p>
</section>
<section id="revised-example-two-sample-t-test-with-additional-insights" class="level3">
<h3 class="anchored" data-anchor-id="revised-example-two-sample-t-test-with-additional-insights">Revised Example: Two-sample T-test with Additional Insights</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate performance scores for two groups</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>trained_employees <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">75</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Employees who received training</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>untrained_employees <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">70</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Employees who did not receive training</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary statistics</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  55.33   68.29   74.26   74.53   79.89   92.87 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(untrained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  54.51   66.97   70.48   71.78   77.57   91.69 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate standard deviations</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(trained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.810307</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(untrained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.351279</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform two-sample t-test to compare the mean performance scores between trained and untrained employees</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(trained_employees, untrained_employees)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test result</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  trained_employees and untrained_employees
t = 1.1672, df = 56.559, p-value = 0.248
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.965426  7.456584
sample estimates:
mean of x mean of y 
 74.52896  71.78338 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">score =</span> <span class="fu">c</span>(trained_employees, untrained_employees),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Trained"</span>, <span class="st">"Untrained"</span>), <span class="at">each =</span> <span class="dv">30</span>))</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Performance Scores by Training Status"</span>, <span class="at">x =</span> <span class="st">"Group"</span>, <span class="at">y =</span> <span class="st">"Performance Score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="1.5-Hypothesis-Testing_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Summary Statistics and Standard Deviations:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  55.33   68.29   74.26   74.53   79.89   92.87 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 52.27   66.75   74.71   75.10   82.31   96.20 </span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(untrained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  54.51   66.97   70.48   71.78   77.57   91.69 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 55.30   65.04   73.78   70.16   77.65   83.63 </span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviations</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(trained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.810307</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># [1] 10.34925</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(untrained_employees)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.351279</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># [1] 9.403503</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation:</h3>
<ul>
<li><strong>Performance Scores:</strong>
<ul>
<li><strong>Trained Employees:</strong> Mean = 75.10, SD = 10.35</li>
<li><strong>Untrained Employees:</strong> Mean = 70.16, SD = 9.40</li>
</ul></li>
<li><strong>T-test Result:</strong>
<ul>
<li><strong>t:</strong> Test statistic (1.6201)</li>
<li><strong>df:</strong> Degrees of freedom (57.635)</li>
<li><strong>p-value:</strong> Probability of observing the data if the null hypothesis is true (0.1104)</li>
<li><strong>95% Confidence Interval:</strong> Range within which the true mean difference lies with 95% confidence (-1.084326 to 9.984326)</li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Although the means appear different, the standard deviations are relatively high (10.35 and 9.40), which means there is substantial variability within each group. The p-value (0.1104) indicates that the observed difference could be due to random chance, and it is not statistically significant at the 0.05 level.</p>
<p>The boxplot visualization also helps to see the overlap in the distributions of the scores between the two groups, reinforcing the result that the difference is not statistically significant.</p>
<p>This revised example shows how variability and sample size can impact the results of a t-test, and why it’s essential to consider these factors when interpreting the results.</p>
</section>
<section id="paired-sample-t-test" class="level3">
<h3 class="anchored" data-anchor-id="paired-sample-t-test">3. Paired Sample T-test</h3>
<p><strong>Use:</strong> To compare the means of two related samples (e.g., before and after measurements on the same subjects).</p>
<p><strong>Assumptions:</strong> - The differences between the paired observations are normally distributed. - The pairs are independent of each other.</p>
<p><strong>Example:</strong>- Suppose we want to test if a training program has significantly improved employee productivity scores by comparing their productivity before and after the training.</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate productivity scores before and after the training</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>productivity_before <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">2</span>)  <span class="co"># Productivity scores before training</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>productivity_after <span class="ot">&lt;-</span> productivity_before <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fl">0.5</span>, <span class="at">sd =</span> <span class="dv">1</span>)  <span class="co"># Productivity scores after training</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform paired sample t-test to compare the mean productivity scores before and after training</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(productivity_before, productivity_after, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the productivity scores</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(productivity_before)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.879049 4.539645 8.117417 5.141017 5.258575 8.430130 5.921832 2.469878
 [9] 3.626294 4.108676 7.448164 5.719628 5.801543 5.221365 3.888318 8.573826
[17] 5.995701 1.066766 6.402712 4.054417 2.864353 4.564050 2.947991 3.542218
[25] 3.749921 1.626613 6.675574 5.306746 2.723726 7.507630</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(productivity_after)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 4.805513 4.744574 9.512542 6.519150 6.580157 9.618770 6.975750 2.907966
 [9] 3.820332 4.228205 7.253457 6.011710 5.036147 7.890321 5.596280 7.950718
[17] 6.092816 1.100110 7.682677 4.471048 3.617671 5.035503 3.405121 5.410820
[25] 4.024150 3.643084 5.626821 6.391360 3.347580 8.223571</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the t-test result</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  productivity_before and productivity_after
t = -4.4489, df = 29, p-value = 0.0001169
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.9901802 -0.3664964
sample estimates:
mean difference 
     -0.6783383 </code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Productivity Scores:</strong></p>
<ul>
<li><p><strong>Before Training:</strong> Generated productivity scores with a mean of approximately 5.</p></li>
<li><p><strong>After Training:</strong> Generated productivity scores that are on average higher than before training.</p></li>
</ul></li>
<li><p><strong>T-test Result:</strong></p>
<ul>
<li><p><strong>t:</strong> Test statistic (-4.4489)</p></li>
<li><p><strong>df:</strong> Degrees of freedom (29)</p></li>
<li><p><strong>p-value:</strong> Probability of observing the data if the null hypothesis is true (0.0001169)</p></li>
<li><p><strong>95% Confidence Interval:</strong> Range within which the true mean difference lies with 95% confidence (-0.9901802 to -0.3664964=)</p></li>
<li><p><strong>Mean of the Differences:</strong> Average difference in productivity scores before and after training (-0.6783383)</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.0001169) is less than the common significance level (0.05), we reject the null hypothesis.</p>
<p>This indicates that there is a significant difference in productivity scores before and after the training, with productivity increasing after the training program.</p>
</section>
<section id="one-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova">4. One-way ANOVA</h3>
<p><strong>Use:</strong> To compare the means of three or more groups to see if at least one mean is different.</p>
<p><strong>Assumptions:</strong> - The data in each group is normally distributed. - The variances of the populations are equal (homogeneity of variances). - The samples are independent.</p>
<p><strong>Example:</strong>- Suppose we want to test if there is a significant difference in customer satisfaction scores among three different service plans (Basic, Standard, Premium).</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate satisfaction scores for three different service plans</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>basic_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">2</span>)  <span class="co"># Basic Plan</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>standard_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">6</span>, <span class="at">sd =</span> <span class="dv">2</span>)  <span class="co"># Standard Plan</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>premium_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">2</span>)  <span class="co"># Premium Plan</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> <span class="fu">c</span>(basic_plan, standard_plan, premium_plan),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">plan =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Basic"</span>, <span class="st">"Standard"</span>, <span class="st">"Premium"</span>), <span class="at">each =</span> <span class="dv">30</span>))</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(satisfaction <span class="sc">~</span> plan, <span class="at">data =</span> data)</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
plan         2  71.77   35.88   11.14 4.94e-05 ***
Residuals   87 280.30    3.22                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Groups (Service Plans):</strong></p>
<ul>
<li><p><strong>Basic Plan:</strong> Mean satisfaction score of 5</p></li>
<li><p><strong>Standard Plan:</strong> Mean satisfaction score of 6</p></li>
<li><p><strong>Premium Plan:</strong> Mean satisfaction score of 7</p></li>
</ul></li>
<li><p><strong>ANOVA Summary:</strong></p>
<ul>
<li><p><strong>Df:</strong> Degrees of freedom</p></li>
<li><p><strong>Sum Sq:</strong> Sum of squares</p></li>
<li><p><strong>Mean Sq:</strong> Mean squares</p></li>
<li><p><strong>F value:</strong> F statistic</p></li>
<li><p><strong>Pr(&gt;F):</strong> p-value for the F-test</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong></p>
<p>- If the p-value is less than the significance level (e.g., 0.05), reject the null hypothesis.</p>
<p>Since the p-value (4.94e-5) is less than the common significance level (0.05), we reject the null hypothesis.</p>
<p>This indicates that there is a significant difference in customer satisfaction scores among the three service plans.</p>
</section>
<section id="chi-square-test-for-independence" class="level3">
<h3 class="anchored" data-anchor-id="chi-square-test-for-independence">5. Chi-square Test for Independence</h3>
<p><strong>Use:</strong> To test if there is a significant association between two categorical variables.</p>
<p><strong>Assumptions:</strong> - The data is in the form of counts or frequencies. - The observations are independent. - The expected frequency in each cell of the contingency table is at least 5.</p>
<p><strong>Example:</strong>- Suppose we want to test if there is a significant association between the type of marketing campaign (Email vs.&nbsp;Social Media) and customer response (Purchased vs.&nbsp;Not Purchased).</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a contingency table for marketing campaigns and customer response</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Rows: Customer Response (Purchased, Not Purchased)</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Columns: Marketing Campaign (Email, Social Media)</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>campaign_data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">80</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(campaign_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Email"</span>, <span class="st">"Social Media"</span>)</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(campaign_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Purchased"</span>, <span class="st">"Not Purchased"</span>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the contingency table</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(campaign_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Email Social Media
Purchased        20           30
Not Purchased    50           80</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform chi-squared test</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>chi_square_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(campaign_data)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the test result</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chi_square_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  campaign_data
X-squared = 0.00035964, df = 1, p-value = 0.9849</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>- If the p-value is less than the significance level (e.g., 0.05), reject the null hypothesis.</p>
<p>Here, the p-value is 0.9849, so we fail to reject the null hypothesis, indicating no significant association between the groups and categories.</p>
<p>This indicates that there is no significant association between the type of marketing campaign (Email vs.&nbsp;Social Media) and customer response (Purchased vs.&nbsp;Not Purchased).</p>
</section>
<section id="mann-whitney-u-test-wilcoxon-rank-sum-test" class="level3">
<h3 class="anchored" data-anchor-id="mann-whitney-u-test-wilcoxon-rank-sum-test">6. Mann-Whitney U Test (Wilcoxon Rank-Sum Test)</h3>
<p><strong>Use:</strong> To compare the distributions of two independent samples when the assumptions for a t-test are not met.</p>
<p><strong>Assumptions:</strong> - The samples are independent. - The data is ordinal or continuous. - The distributions of the two groups are similar in shape.</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate non-normally distributed sales performance scores for two sales teams using the exponential distribution</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>team_A_sales <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)  <span class="co"># Sales performance scores for Team A</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>team_B_sales <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)  <span class="co"># Sales performance scores for Team B</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Wilcoxon Rank-Sum Test to compare the sales performance scores between Team A and Team B</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>wilcox_test_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(team_A_sales, team_B_sales)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the sales performance scores</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(team_A_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  4.2172863  2.8830514  6.6452743  0.1578868  0.2810549  1.5825061
 [7]  1.5711365  0.7263340 13.6311823  0.1457672  5.0241503  2.4010736
[13]  1.4050681  1.8855892  0.9414202  4.2489306  7.8160177  2.3938021
[19]  2.9546742 20.2050586  4.2157487  4.8293561  7.4263790  6.7402224
[25]  5.8426449  8.0292617  7.4837143  7.8532627  0.1588387  2.9892485</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(team_B_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 13.0070385  3.0396944  1.5573469 15.5813527  7.3741544  4.7440906
 [7]  3.7756805  7.5278460  3.5321079  6.7757402  2.5221888 43.2660455
[13]  5.0743318  1.3532520  6.6020329 13.4898342  8.1824058  3.4583500
[19] 16.3516551  7.8729783  0.5435481  1.8372231  6.4032784  1.8810975
[25]  5.8478409 11.3269399  3.3875316 15.4617680  6.2861745  6.1466481</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Wilcoxon Rank-Sum Test result</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wilcox_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  team_A_sales and team_B_sales
W = 308, p-value = 0.03577
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Sales Performance Scores:</strong></p>
<ul>
<li><p><strong>Team A:</strong> Generated sales performance scores using the exponential distribution with a rate of 1/5.</p></li>
<li><p><strong>Team B:</strong> Generated sales performance scores using the exponential distribution with a rate of 1/6.</p></li>
</ul></li>
<li><p><strong>Wilcoxon Rank-Sum Test Result:</strong></p>
<ul>
<li><p><strong>W:</strong> Test statistic (308)</p></li>
<li><p><strong>p-value:</strong> Probability of observing the data if the null hypothesis is true (0.03577)</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.03577) is less than the common significance level (0.05), we reject the null hypothesis.</p>
<p>This indicates that there is a significant difference in the sales performance scores between Team A and Team B.</p>
<p><strong>Determine where is the difference?</strong></p>
<p>To determine which side the difference lies on, we can look at the medians of the two groups and the alternative hypothesis of the Wilcoxon Rank-Sum Test. Here’s how you can interpret the results and determine which group has higher values:</p>
<ol type="1">
<li><strong>Check the Medians of Both Groups:</strong> Calculate and compare the medians of the two groups.</li>
<li><strong>Interpret the Alternative Hypothesis:</strong> The alternative hypothesis of the Wilcoxon Rank-Sum Test is that the true location shift between the two groups is not equal to zero. If the p-value is significant and the median of one group is higher than the other, you can infer the direction of the difference.</li>
</ol>
</section>
<section id="example-determining-the-direction-of-the-difference" class="level3">
<h3 class="anchored" data-anchor-id="example-determining-the-direction-of-the-difference">Example: Determining the Direction of the Difference</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate non-normally distributed sales performance scores for two sales teams using the exponential distribution</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>team_A_sales <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)  <span class="co"># Sales performance scores for Team A</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>team_B_sales <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)  <span class="co"># Sales performance scores for Team B</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Wilcoxon Rank-Sum Test to compare the sales performance scores between Team A and Team B</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>wilcox_test_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(team_A_sales, team_B_sales)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the sales performance scores</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(team_A_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  4.2172863  2.8830514  6.6452743  0.1578868  0.2810549  1.5825061
 [7]  1.5711365  0.7263340 13.6311823  0.1457672  5.0241503  2.4010736
[13]  1.4050681  1.8855892  0.9414202  4.2489306  7.8160177  2.3938021
[19]  2.9546742 20.2050586  4.2157487  4.8293561  7.4263790  6.7402224
[25]  5.8426449  8.0292617  7.4837143  7.8532627  0.1588387  2.9892485</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(team_B_sales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 13.0070385  3.0396944  1.5573469 15.5813527  7.3741544  4.7440906
 [7]  3.7756805  7.5278460  3.5321079  6.7757402  2.5221888 43.2660455
[13]  5.0743318  1.3532520  6.6020329 13.4898342  8.1824058  3.4583500
[19] 16.3516551  7.8729783  0.5435481  1.8372231  6.4032784  1.8810975
[25]  5.8478409 11.3269399  3.3875316 15.4617680  6.2861745  6.1466481</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Wilcoxon Rank-Sum Test result</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wilcox_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  team_A_sales and team_B_sales
W = 308, p-value = 0.03577
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and print the medians of the two groups</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>median_A <span class="ot">&lt;-</span> <span class="fu">median</span>(team_A_sales)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>median_B <span class="ot">&lt;-</span> <span class="fu">median</span>(team_B_sales)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Team A:"</span>, median_A))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Team A: 3.60249855605114"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Team B:"</span>, median_B))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Team B: 6.21641126927648"</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation:</h3>
<ul>
<li><strong>Medians:</strong>
<ul>
<li><strong>Median of Team A:</strong> 3.60249855605114</li>
<li><strong>Median of Team B:</strong> 6.21641126927648</li>
</ul></li>
<li><strong>Wilcoxon Rank-Sum Test Result:</strong>
<ul>
<li><strong>W:</strong> Test statistic (308)</li>
<li><strong>p-value:</strong> 0.03577</li>
<li><strong>Alternative Hypothesis:</strong> True location shift is not equal to 0</li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.03577) is less than the significance level (0.05), we reject the null hypothesis, indicating that there is a significant difference in the sales performance scores between Team A and Team B.</p>
<p>Comparing the medians, Team B has a higher median sales performance score (6.216) compared to Team A (3.60). Therefore, Team B performs significantly better than Team A.</p>
<p>This approach helps us determine not only whether there is a significant difference but also which group has higher values based on their medians.</p>
</section>
<section id="wilcoxon-signed-rank-test" class="level3">
<h3 class="anchored" data-anchor-id="wilcoxon-signed-rank-test">7. Wilcoxon Signed-Rank Test</h3>
<p><strong>Use:</strong> To compare the distributions of two related samples when the assumptions for a paired t-test are not met.</p>
<p><strong>Assumptions:</strong> - The differences between the paired observations are symmetrically distributed. - The pairs are independent.</p>
<p><strong>Example:</strong>- Suppose we want to test if a new process has significantly improved employee productivity scores by comparing their productivity before and after the implementation of the new process using a non-parametric test (Wilcoxon Signed-Rank Test).</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate non-normally distributed productivity scores before and after the implementation of a new process using the exponential distribution</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>productivity_before <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)  <span class="co"># Productivity scores before the new process</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>productivity_after <span class="ot">&lt;-</span> productivity_before <span class="sc">+</span> <span class="fu">rexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)  <span class="co"># Productivity scores after the new process</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Wilcoxon Signed-Rank Test to compare the productivity scores before and after the new process</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>wilcox_test_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(productivity_before, productivity_after, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the productivity scores</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(productivity_before)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  4.2172863  2.8830514  6.6452743  0.1578868  0.2810549  1.5825061
 [7]  1.5711365  0.7263340 13.6311823  0.1457672  5.0241503  2.4010736
[13]  1.4050681  1.8855892  0.9414202  4.2489306  7.8160177  2.3938021
[19]  2.9546742 20.2050586  4.2157487  4.8293561  7.4263790  6.7402224
[25]  5.8426449  8.0292617  7.4837143  7.8532627  0.1588387  2.9892485</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(productivity_after)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 17.224325  5.922746  8.202621 15.739239  7.655209  6.326597  5.346817
 [8]  8.254180 17.163290  6.921507  7.546339 45.667119  6.479400  3.238841
[15]  7.543453 17.738765 15.998423  5.852152 19.306329 28.078037  4.759297
[22]  6.666579 13.829657  8.621320 11.690486 19.356202 10.871246 23.315031
[29]  6.445013  9.135897</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Wilcoxon Signed-Rank Test result</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wilcox_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank exact test

data:  productivity_before and productivity_after
V = 0, p-value = 1.863e-09
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and print the medians of the two groups</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>median_before <span class="ot">&lt;-</span> <span class="fu">median</span>(productivity_before)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>median_after <span class="ot">&lt;-</span> <span class="fu">median</span>(productivity_after)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Productivity Before:"</span>, median_before))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Productivity Before: 3.60249855605114"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Productivity After:"</span>, median_after))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Productivity After: 8.43775000078458"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Productivity Scores:</strong></p>
<ul>
<li><p><strong>Before the New Process:</strong> Generated productivity scores using the exponential distribution with a rate of 1/5.</p></li>
<li><p><strong>After the New Process:</strong> Generated productivity scores using the exponential distribution with a rate of 1/6.</p></li>
</ul></li>
<li><p><strong>Wilcoxon Signed-Rank Test Result:</strong></p>
<ul>
<li><p><strong>V:</strong> Test statistic (74)</p></li>
<li><p><strong>p-value:</strong> 1.863e-09</p></li>
<li><p><strong>Alternative Hypothesis:</strong> True location shift is not equal to 0</p></li>
</ul></li>
<li><p><strong>Medians:</strong></p>
<ul>
<li><p><strong>Median of Productivity Before:</strong> 3.6</p></li>
<li><p><strong>Median of Productivity After:</strong> 8.4</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (1.863e-09) is less than the common significance level (0.05), we reject the null hypothesis.</p>
<p>This indicates that there is a significant difference in productivity scores before and after the implementation of the new process, with productivity increasing after the new process.</p>
<p>Comparing the medians, the productivity after the new process (3.6) is higher than before (8.4).</p>
</section>
<section id="kruskal-wallis-test" class="level3">
<h3 class="anchored" data-anchor-id="kruskal-wallis-test">8. Kruskal-Wallis Test</h3>
<p><strong>Use:</strong> To compare the distributions of three or more independent groups when the assumptions for ANOVA are not met.</p>
<p><strong>Assumptions:</strong></p>
<p>- The samples are independent.</p>
<p>- The data is ordinal or continuous.</p>
<p>- The distributions of the groups are similar in shape.</p>
<p><strong>Example:</strong>- Suppose we want to test if there is a significant difference in customer satisfaction scores among three different service plans (Basic, Standard, and Premium) using a non-parametric test (Kruskal-Wallis Test).</p>
<p><strong>Code:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate customer satisfaction scores for three different service plans</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>basic_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">2</span>)     <span class="co"># Satisfaction scores for Basic Plan</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>standard_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">6</span>, <span class="at">sd =</span> <span class="dv">2</span>)  <span class="co"># Satisfaction scores for Standard Plan</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>premium_plan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">7</span>, <span class="at">sd =</span> <span class="dv">2</span>)   <span class="co"># Satisfaction scores for Premium Plan</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> <span class="fu">c</span>(basic_plan, standard_plan, premium_plan),</span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">plan =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Basic"</span>, <span class="st">"Standard"</span>, <span class="st">"Premium"</span>), <span class="at">each =</span> <span class="dv">30</span>))</span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb73-14"><a href="#cb73-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-15"><a href="#cb73-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Kruskal-Wallis Test to compare the satisfaction scores among the three service plans</span></span>
<span id="cb73-16"><a href="#cb73-16" aria-hidden="true" tabindex="-1"></a>kruskal_test_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(satisfaction <span class="sc">~</span> plan, <span class="at">data =</span> data)</span>
<span id="cb73-17"><a href="#cb73-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-18"><a href="#cb73-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the satisfaction scores</span></span>
<span id="cb73-19"><a href="#cb73-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   satisfaction     plan
1      3.879049    Basic
2      4.539645    Basic
3      8.117417    Basic
4      5.141017    Basic
5      5.258575    Basic
6      8.430130    Basic
7      5.921832    Basic
8      2.469878    Basic
9      3.626294    Basic
10     4.108676    Basic
11     7.448164    Basic
12     5.719628    Basic
13     5.801543    Basic
14     5.221365    Basic
15     3.888318    Basic
16     8.573826    Basic
17     5.995701    Basic
18     1.066766    Basic
19     6.402712    Basic
20     4.054417    Basic
21     2.864353    Basic
22     4.564050    Basic
23     2.947991    Basic
24     3.542218    Basic
25     3.749921    Basic
26     1.626613    Basic
27     6.675574    Basic
28     5.306746    Basic
29     2.723726    Basic
30     7.507630    Basic
31     6.852928 Standard
32     5.409857 Standard
33     7.790251 Standard
34     7.756267 Standard
35     7.643162 Standard
36     7.377281 Standard
37     7.107835 Standard
38     5.876177 Standard
39     5.388075 Standard
40     5.239058 Standard
41     4.610586 Standard
42     5.584165 Standard
43     3.469207 Standard
44    10.337912 Standard
45     8.415924 Standard
46     3.753783 Standard
47     5.194230 Standard
48     5.066689 Standard
49     7.559930 Standard
50     5.833262 Standard
51     6.506637 Standard
52     5.942906 Standard
53     5.914259 Standard
54     8.737205 Standard
55     5.548458 Standard
56     9.032941 Standard
57     2.902494 Standard
58     7.169227 Standard
59     6.247708 Standard
60     6.431883 Standard
61     7.759279  Premium
62     5.995353  Premium
63     6.333585  Premium
64     4.962849  Premium
65     4.856418  Premium
66     7.607057  Premium
67     7.896420  Premium
68     7.106008  Premium
69     8.844535  Premium
70    11.100169  Premium
71     6.017938  Premium
72     2.381662  Premium
73     9.011477  Premium
74     5.581598  Premium
75     5.623983  Premium
76     9.051143  Premium
77     6.430454  Premium
78     4.558565  Premium
79     7.362607  Premium
80     6.722217  Premium
81     7.011528  Premium
82     7.770561  Premium
83     6.258680  Premium
84     8.288753  Premium
85     6.559027  Premium
86     7.663564  Premium
87     9.193678  Premium
88     7.870363  Premium
89     6.348137  Premium
90     9.297615  Premium</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Kruskal-Wallis Test result</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(kruskal_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  satisfaction by plan
Kruskal-Wallis chi-squared = 17.693, df = 2, p-value = 0.0001439</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and print the medians of the three groups</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>median_basic <span class="ot">&lt;-</span> <span class="fu">median</span>(basic_plan)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>median_standard <span class="ot">&lt;-</span> <span class="fu">median</span>(standard_plan)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>median_premium <span class="ot">&lt;-</span> <span class="fu">median</span>(premium_plan)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Basic Plan:"</span>, median_basic))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Basic Plan: 4.85253347676628"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Standard Plan:"</span>, median_standard))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Standard Plan: 6.09530748849591"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Median of Premium Plan:"</span>, median_premium))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Median of Premium Plan: 7.05876841263039"</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p><strong>Customer Satisfaction Scores:</strong></p>
<ul>
<li><p><strong>Basic Plan:</strong> Generated satisfaction scores with a mean of approximately 5.</p></li>
<li><p><strong>Standard Plan:</strong> Generated satisfaction scores with a mean of approximately 6.</p></li>
<li><p><strong>Premium Plan:</strong> Generated satisfaction scores with a mean of approximately 7.</p></li>
</ul></li>
<li><p><strong>Kruskal-Wallis Test Result:</strong></p>
<ul>
<li><p><strong>Kruskal-Wallis chi-squared:</strong> 17.693</p></li>
<li><p><strong>Degrees of Freedom (df):</strong> 2</p></li>
<li><p><strong>p-value:</strong> 0.0001439</p></li>
</ul></li>
<li><p><strong>Medians:</strong></p>
<ul>
<li><p><strong>Median of Basic Plan:</strong> 4.85</p></li>
<li><p><strong>Median of Standard Plan:</strong> 6.09</p></li>
<li><p><strong>Median of Premium Plan:</strong> 7.05</p></li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> Since the p-value (0.0001439) is less than the common significance level (0.05), we reject the null hypothesis.</p>
<p>This indicates that there is a significant difference in customer satisfaction scores among the three service plans.</p>
<p>Comparing the medians, the Premium Plan has the highest median satisfaction score (7.05), followed by the Standard Plan (6.09), and then the Basic Plan (4.85).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>